# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
