# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 21:39
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170916_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=0, upload_to='users/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
