# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=0, help_text='A short label, generally used in URLs.'),
            preserve_default=False,
        ),
    ]
