# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 16:45
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Film duration, in minutes.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='Price of one ticket, in dollars.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='When film was releaded.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_time',
            field=models.DateTimeField(help_text='When film will be show in cinema.'),
        ),
    ]
