# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='pirates', help_text='A short label, generally used in URLs.'),
            preserve_default=False,
        ),
    ]
