# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='place',
            field=models.CharField(blank=True, choices=[((('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')), 'row1'), ((('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')), 'row2'), ((('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')), 'row3'), ((('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')), 'row4'), ((('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')), 'row5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('action', 'Action'), ('adventure', 'Adventure'), ('crime', 'Crime'), ('drama', 'Drama')], max_length=40),
        ),
    ]
