# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20170917_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='place',
            field=models.CharField(blank=True, choices=[('1', '1'), ('1', '1'), ('1', '1')], max_length=100),
        ),
    ]
