# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20170917_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1_place1', models.BooleanField(default=False)),
                ('row1_place2', models.BooleanField(default=False)),
                ('row1_place3', models.BooleanField(default=False)),
                ('row1_place4', models.BooleanField(default=False)),
                ('row1_place5', models.BooleanField(default=False)),
                ('row1_place6', models.BooleanField(default=False)),
                ('row1_place7', models.BooleanField(default=False)),
                ('row1_place8', models.BooleanField(default=False)),
                ('row2_place1', models.BooleanField(default=False)),
                ('row2_place2', models.BooleanField(default=False)),
                ('row2_place3', models.BooleanField(default=False)),
                ('row2_place4', models.BooleanField(default=False)),
                ('row2_place5', models.BooleanField(default=False)),
                ('row2_place6', models.BooleanField(default=False)),
                ('row2_place7', models.BooleanField(default=False)),
                ('row2_place8', models.BooleanField(default=False)),
                ('row3_place1', models.BooleanField(default=False)),
                ('row3_place2', models.BooleanField(default=False)),
                ('row3_place3', models.BooleanField(default=False)),
                ('row3_place4', models.BooleanField(default=False)),
                ('row3_place5', models.BooleanField(default=False)),
                ('row3_place6', models.BooleanField(default=False)),
                ('row3_place7', models.BooleanField(default=False)),
                ('row3_place8', models.BooleanField(default=False)),
                ('row4_place1', models.BooleanField(default=False)),
                ('row4_place2', models.BooleanField(default=False)),
                ('row4_place3', models.BooleanField(default=False)),
                ('row4_place4', models.BooleanField(default=False)),
                ('row4_place5', models.BooleanField(default=False)),
                ('row4_place6', models.BooleanField(default=False)),
                ('row4_place7', models.BooleanField(default=False)),
                ('row4_place8', models.BooleanField(default=False)),
                ('row5_place1', models.BooleanField(default=False)),
                ('row5_place2', models.BooleanField(default=False)),
                ('row5_place3', models.BooleanField(default=False)),
                ('row5_place4', models.BooleanField(default=False)),
                ('row5_place5', models.BooleanField(default=False)),
                ('row5_place6', models.BooleanField(default=False)),
                ('row5_place7', models.BooleanField(default=False)),
                ('row5_place8', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='place',
        ),
        migrations.AddField(
            model_name='places',
            name='chain_models',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
