# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20170918_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='chain_models',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
